SET IDENTITY_INSERT [dbo].[COUNTRY] ON
INSERT INTO [dbo].[COUNTRY] ([Country_ID], [Name]) VALUES (1, N'Russia')
INSERT INTO [dbo].[COUNTRY] ([Country_ID], [Name]) VALUES (2, N'Germany')
INSERT INTO [dbo].[COUNTRY] ([Country_ID], [Name]) VALUES (3, N'United Kingdom')
INSERT INTO [dbo].[COUNTRY] ([Country_ID], [Name]) VALUES (4, N'France')
INSERT INTO [dbo].[COUNTRY] ([Country_ID], [Name]) VALUES (5, N'Italy')
INSERT INTO [dbo].[COUNTRY] ([Country_ID], [Name]) VALUES (6, N'Spain')
INSERT INTO [dbo].[COUNTRY] ([Country_ID], [Name]) VALUES (7, N'Ukraine')
INSERT INTO [dbo].[COUNTRY] ([Country_ID], [Name]) VALUES (8, N'Poland')
INSERT INTO [dbo].[COUNTRY] ([Country_ID], [Name]) VALUES (9, N'Romania')
INSERT INTO [dbo].[COUNTRY] ([Country_ID], [Name]) VALUES (10, N'Netherlands')
INSERT INTO [dbo].[COUNTRY] ([Country_ID], [Name]) VALUES (11, N'Belgium')
INSERT INTO [dbo].[COUNTRY] ([Country_ID], [Name]) VALUES (12, N'Czech Republic')
INSERT INTO [dbo].[COUNTRY] ([Country_ID], [Name]) VALUES (13, N'Greece')
INSERT INTO [dbo].[COUNTRY] ([Country_ID], [Name]) VALUES (14, N'Portugal')
INSERT INTO [dbo].[COUNTRY] ([Country_ID], [Name]) VALUES (15, N'Sweden')
INSERT INTO [dbo].[COUNTRY] ([Country_ID], [Name]) VALUES (16, N'Hungary')
INSERT INTO [dbo].[COUNTRY] ([Country_ID], [Name]) VALUES (17, N'Belarus')
INSERT INTO [dbo].[COUNTRY] ([Country_ID], [Name]) VALUES (18, N'Austria')
INSERT INTO [dbo].[COUNTRY] ([Country_ID], [Name]) VALUES (19, N'Serbia')
INSERT INTO [dbo].[COUNTRY] ([Country_ID], [Name]) VALUES (20, N'Switzerland')
INSERT INTO [dbo].[COUNTRY] ([Country_ID], [Name]) VALUES (21, N'Bulgaria')
INSERT INTO [dbo].[COUNTRY] ([Country_ID], [Name]) VALUES (22, N'Denmark')
INSERT INTO [dbo].[COUNTRY] ([Country_ID], [Name]) VALUES (23, N'Finland')
INSERT INTO [dbo].[COUNTRY] ([Country_ID], [Name]) VALUES (24, N'Slovakia')
INSERT INTO [dbo].[COUNTRY] ([Country_ID], [Name]) VALUES (25, N'Norway')
INSERT INTO [dbo].[COUNTRY] ([Country_ID], [Name]) VALUES (26, N'Ireland')
INSERT INTO [dbo].[COUNTRY] ([Country_ID], [Name]) VALUES (27, N'Croatia')
INSERT INTO [dbo].[COUNTRY] ([Country_ID], [Name]) VALUES (28, N'Moldova')
INSERT INTO [dbo].[COUNTRY] ([Country_ID], [Name]) VALUES (29, N'Bosnia and Herzegovina')
INSERT INTO [dbo].[COUNTRY] ([Country_ID], [Name]) VALUES (30, N'Albinia')
INSERT INTO [dbo].[COUNTRY] ([Country_ID], [Name]) VALUES (31, N'Lithuania')
INSERT INTO [dbo].[COUNTRY] ([Country_ID], [Name]) VALUES (32, N'North Macedonia')
INSERT INTO [dbo].[COUNTRY] ([Country_ID], [Name]) VALUES (33, N'Slovenia')
INSERT INTO [dbo].[COUNTRY] ([Country_ID], [Name]) VALUES (34, N'Latvia')
INSERT INTO [dbo].[COUNTRY] ([Country_ID], [Name]) VALUES (35, N'Estonia')
INSERT INTO [dbo].[COUNTRY] ([Country_ID], [Name]) VALUES (36, N'Montenegro')
INSERT INTO [dbo].[COUNTRY] ([Country_ID], [Name]) VALUES (37, N'Luxembourg')
INSERT INTO [dbo].[COUNTRY] ([Country_ID], [Name]) VALUES (38, N'Malta')
INSERT INTO [dbo].[COUNTRY] ([Country_ID], [Name]) VALUES (39, N'Iceland')
INSERT INTO [dbo].[COUNTRY] ([Country_ID], [Name]) VALUES (40, N'Andorra')
INSERT INTO [dbo].[COUNTRY] ([Country_ID], [Name]) VALUES (41, N'Monaco')
INSERT INTO [dbo].[COUNTRY] ([Country_ID], [Name]) VALUES (42, N'Liechtenstein')
INSERT INTO [dbo].[COUNTRY] ([Country_ID], [Name]) VALUES (43, N'San Marino')
INSERT INTO [dbo].[COUNTRY] ([Country_ID], [Name]) VALUES (44, N'Holy See')
INSERT INTO [dbo].[COUNTRY] ([Country_ID], [Name]) VALUES (45, N'Channel Islands')
INSERT INTO [dbo].[COUNTRY] ([Country_ID], [Name]) VALUES (46, N'Isle of Man')
INSERT INTO [dbo].[COUNTRY] ([Country_ID], [Name]) VALUES (47, N'Faeroe Islands')
INSERT INTO [dbo].[COUNTRY] ([Country_ID], [Name]) VALUES (48, N'Gibraltar')
INSERT INTO [dbo].[COUNTRY] ([Country_ID], [Name]) VALUES (49, N'South Africa')
SET IDENTITY_INSERT [dbo].[COUNTRY] OFF
