SET IDENTITY_INSERT [dbo].[REGION] ON
INSERT INTO [dbo].[REGION] ([Region_ID], [Country_ID], [Name]) VALUES (1, 49, N'Gauteng')
INSERT INTO [dbo].[REGION] ([Region_ID], [Country_ID], [Name]) VALUES (2, 49, N'North West')
INSERT INTO [dbo].[REGION] ([Region_ID], [Country_ID], [Name]) VALUES (3, 49, N'Eastern Cape')
INSERT INTO [dbo].[REGION] ([Region_ID], [Country_ID], [Name]) VALUES (4, 49, N'Western Cape')
INSERT INTO [dbo].[REGION] ([Region_ID], [Country_ID], [Name]) VALUES (5, 49, N'Northern Cape')
INSERT INTO [dbo].[REGION] ([Region_ID], [Country_ID], [Name]) VALUES (6, 49, N'Free State')
INSERT INTO [dbo].[REGION] ([Region_ID], [Country_ID], [Name]) VALUES (7, 49, N'Limpopo')
INSERT INTO [dbo].[REGION] ([Region_ID], [Country_ID], [Name]) VALUES (8, 49, N'Mpumalunga')
INSERT INTO [dbo].[REGION] ([Region_ID], [Country_ID], [Name]) VALUES (9, 49, N'KwaZulu-Natal')
INSERT INTO [dbo].[REGION] ([Region_ID], [Country_ID], [Name]) VALUES (10, 1, N'Amur')
INSERT INTO [dbo].[REGION] ([Region_ID], [Country_ID], [Name]) VALUES (11, 1, N'Arkhangelsk')
INSERT INTO [dbo].[REGION] ([Region_ID], [Country_ID], [Name]) VALUES (13, 1, N'Astrakhan')
INSERT INTO [dbo].[REGION] ([Region_ID], [Country_ID], [Name]) VALUES (14, 1, N'Belgorod')
INSERT INTO [dbo].[REGION] ([Region_ID], [Country_ID], [Name]) VALUES (15, 1, N'Bryansk')
INSERT INTO [dbo].[REGION] ([Region_ID], [Country_ID], [Name]) VALUES (16, 1, N'Chelyanbinsk')
INSERT INTO [dbo].[REGION] ([Region_ID], [Country_ID], [Name]) VALUES (17, 1, N'Irkutsk')
INSERT INTO [dbo].[REGION] ([Region_ID], [Country_ID], [Name]) VALUES (18, 1, N'Ivanovo')
INSERT INTO [dbo].[REGION] ([Region_ID], [Country_ID], [Name]) VALUES (19, 1, N'Kaliningrad')
INSERT INTO [dbo].[REGION] ([Region_ID], [Country_ID], [Name]) VALUES (20, 1, N'Kaluga')
INSERT INTO [dbo].[REGION] ([Region_ID], [Country_ID], [Name]) VALUES (21, 1, N'Kemerovo')
INSERT INTO [dbo].[REGION] ([Region_ID], [Country_ID], [Name]) VALUES (22, 1, N'Kirov')
INSERT INTO [dbo].[REGION] ([Region_ID], [Country_ID], [Name]) VALUES (23, 1, N'Kostroma')
INSERT INTO [dbo].[REGION] ([Region_ID], [Country_ID], [Name]) VALUES (24, 1, N'Kurgan')
INSERT INTO [dbo].[REGION] ([Region_ID], [Country_ID], [Name]) VALUES (25, 1, N'Kursk')
INSERT INTO [dbo].[REGION] ([Region_ID], [Country_ID], [Name]) VALUES (26, 1, N'Leningrad')
INSERT INTO [dbo].[REGION] ([Region_ID], [Country_ID], [Name]) VALUES (27, 1, N'Lipetsk')
INSERT INTO [dbo].[REGION] ([Region_ID], [Country_ID], [Name]) VALUES (28, 1, N'Magadan')
INSERT INTO [dbo].[REGION] ([Region_ID], [Country_ID], [Name]) VALUES (29, 1, N'Moscow')
INSERT INTO [dbo].[REGION] ([Region_ID], [Country_ID], [Name]) VALUES (30, 1, N'Murmansk')
INSERT INTO [dbo].[REGION] ([Region_ID], [Country_ID], [Name]) VALUES (31, 1, N'Nizhny Novgorod')
INSERT INTO [dbo].[REGION] ([Region_ID], [Country_ID], [Name]) VALUES (32, 1, N'Novgorod')
INSERT INTO [dbo].[REGION] ([Region_ID], [Country_ID], [Name]) VALUES (33, 1, N'Novosibirsk')
INSERT INTO [dbo].[REGION] ([Region_ID], [Country_ID], [Name]) VALUES (34, 1, N'Omsk')
INSERT INTO [dbo].[REGION] ([Region_ID], [Country_ID], [Name]) VALUES (35, 1, N'Orenburg')
INSERT INTO [dbo].[REGION] ([Region_ID], [Country_ID], [Name]) VALUES (37, 1, N'Oryol')
INSERT INTO [dbo].[REGION] ([Region_ID], [Country_ID], [Name]) VALUES (38, 1, N'Penza')
INSERT INTO [dbo].[REGION] ([Region_ID], [Country_ID], [Name]) VALUES (39, 1, N'Pskov')
INSERT INTO [dbo].[REGION] ([Region_ID], [Country_ID], [Name]) VALUES (40, 1, N'Rostov')
INSERT INTO [dbo].[REGION] ([Region_ID], [Country_ID], [Name]) VALUES (41, 1, N'Ryazan')
INSERT INTO [dbo].[REGION] ([Region_ID], [Country_ID], [Name]) VALUES (42, 1, N'Sakhalin')
INSERT INTO [dbo].[REGION] ([Region_ID], [Country_ID], [Name]) VALUES (43, 1, N'Samara')
INSERT INTO [dbo].[REGION] ([Region_ID], [Country_ID], [Name]) VALUES (44, 1, N'Saratov')
INSERT INTO [dbo].[REGION] ([Region_ID], [Country_ID], [Name]) VALUES (45, 1, N'Smolensk')
INSERT INTO [dbo].[REGION] ([Region_ID], [Country_ID], [Name]) VALUES (46, 1, N'Sverdlovsk')
INSERT INTO [dbo].[REGION] ([Region_ID], [Country_ID], [Name]) VALUES (47, 1, N'Tambov')
INSERT INTO [dbo].[REGION] ([Region_ID], [Country_ID], [Name]) VALUES (48, 1, N'Tomsk')
INSERT INTO [dbo].[REGION] ([Region_ID], [Country_ID], [Name]) VALUES (49, 1, N'Tver')
INSERT INTO [dbo].[REGION] ([Region_ID], [Country_ID], [Name]) VALUES (50, 1, N'Tula')
INSERT INTO [dbo].[REGION] ([Region_ID], [Country_ID], [Name]) VALUES (51, 1, N'Tyumen')
INSERT INTO [dbo].[REGION] ([Region_ID], [Country_ID], [Name]) VALUES (52, 1, N'Ulyanovsk')
INSERT INTO [dbo].[REGION] ([Region_ID], [Country_ID], [Name]) VALUES (53, 1, N'Vladimir')
INSERT INTO [dbo].[REGION] ([Region_ID], [Country_ID], [Name]) VALUES (54, 1, N'Volgograd')
INSERT INTO [dbo].[REGION] ([Region_ID], [Country_ID], [Name]) VALUES (55, 1, N'Vologda')
INSERT INTO [dbo].[REGION] ([Region_ID], [Country_ID], [Name]) VALUES (56, 1, N'Voronezh')
INSERT INTO [dbo].[REGION] ([Region_ID], [Country_ID], [Name]) VALUES (57, 1, N'Yaroslavl')
INSERT INTO [dbo].[REGION] ([Region_ID], [Country_ID], [Name]) VALUES (58, 1, N'Adygea')
INSERT INTO [dbo].[REGION] ([Region_ID], [Country_ID], [Name]) VALUES (59, 1, N'Altai')
INSERT INTO [dbo].[REGION] ([Region_ID], [Country_ID], [Name]) VALUES (60, 1, N'Bashkortostan')
INSERT INTO [dbo].[REGION] ([Region_ID], [Country_ID], [Name]) VALUES (61, 1, N'Buryatia')
INSERT INTO [dbo].[REGION] ([Region_ID], [Country_ID], [Name]) VALUES (62, 1, N'Chechnya')
INSERT INTO [dbo].[REGION] ([Region_ID], [Country_ID], [Name]) VALUES (63, 1, N'Chuvashia')
INSERT INTO [dbo].[REGION] ([Region_ID], [Country_ID], [Name]) VALUES (64, 1, N'Crimea')
INSERT INTO [dbo].[REGION] ([Region_ID], [Country_ID], [Name]) VALUES (65, 1, N'Dagestan')
INSERT INTO [dbo].[REGION] ([Region_ID], [Country_ID], [Name]) VALUES (66, 1, N'Ingushetia')
INSERT INTO [dbo].[REGION] ([Region_ID], [Country_ID], [Name]) VALUES (67, 1, N'Kabardino-Balkaria')
INSERT INTO [dbo].[REGION] ([Region_ID], [Country_ID], [Name]) VALUES (68, 1, N'Kalmykia')
INSERT INTO [dbo].[REGION] ([Region_ID], [Country_ID], [Name]) VALUES (69, 1, N'Karachay-Cherkessia')
INSERT INTO [dbo].[REGION] ([Region_ID], [Country_ID], [Name]) VALUES (70, 1, N'Karelia')
INSERT INTO [dbo].[REGION] ([Region_ID], [Country_ID], [Name]) VALUES (71, 1, N'Khakassia')
INSERT INTO [dbo].[REGION] ([Region_ID], [Country_ID], [Name]) VALUES (72, 1, N'Komi')
INSERT INTO [dbo].[REGION] ([Region_ID], [Country_ID], [Name]) VALUES (73, 1, N'Mari El')
INSERT INTO [dbo].[REGION] ([Region_ID], [Country_ID], [Name]) VALUES (74, 1, N'Mordovia')
INSERT INTO [dbo].[REGION] ([Region_ID], [Country_ID], [Name]) VALUES (75, 1, N'North Ossetia-Alania')
INSERT INTO [dbo].[REGION] ([Region_ID], [Country_ID], [Name]) VALUES (76, 1, N'Yakutia')
INSERT INTO [dbo].[REGION] ([Region_ID], [Country_ID], [Name]) VALUES (77, 1, N'Tartarstan')
INSERT INTO [dbo].[REGION] ([Region_ID], [Country_ID], [Name]) VALUES (78, 1, N'Tuva')
INSERT INTO [dbo].[REGION] ([Region_ID], [Country_ID], [Name]) VALUES (79, 1, N'Udmurtia')
INSERT INTO [dbo].[REGION] ([Region_ID], [Country_ID], [Name]) VALUES (80, 1, N'Barnaul')
INSERT INTO [dbo].[REGION] ([Region_ID], [Country_ID], [Name]) VALUES (81, 1, N'Krasnodar')
INSERT INTO [dbo].[REGION] ([Region_ID], [Country_ID], [Name]) VALUES (82, 1, N'Krasnoyarsk')
INSERT INTO [dbo].[REGION] ([Region_ID], [Country_ID], [Name]) VALUES (83, 1, N'Vladivostok')
INSERT INTO [dbo].[REGION] ([Region_ID], [Country_ID], [Name]) VALUES (84, 1, N'Stavropol')
INSERT INTO [dbo].[REGION] ([Region_ID], [Country_ID], [Name]) VALUES (85, 1, N'Khabarovsk')
INSERT INTO [dbo].[REGION] ([Region_ID], [Country_ID], [Name]) VALUES (86, 1, N'Perm')
INSERT INTO [dbo].[REGION] ([Region_ID], [Country_ID], [Name]) VALUES (87, 1, N'Chita')
INSERT INTO [dbo].[REGION] ([Region_ID], [Country_ID], [Name]) VALUES (88, 1, N'Birobidzhan')
INSERT INTO [dbo].[REGION] ([Region_ID], [Country_ID], [Name]) VALUES (89, 1, N'Naryan-Mar')
INSERT INTO [dbo].[REGION] ([Region_ID], [Country_ID], [Name]) VALUES (90, 1, N'Khanty-Mansiysk')
INSERT INTO [dbo].[REGION] ([Region_ID], [Country_ID], [Name]) VALUES (91, 1, N'Anadyr')
INSERT INTO [dbo].[REGION] ([Region_ID], [Country_ID], [Name]) VALUES (92, 1, N'Salekhard')
INSERT INTO [dbo].[REGION] ([Region_ID], [Country_ID], [Name]) VALUES (93, 1, N'Simferopol')
INSERT INTO [dbo].[REGION] ([Region_ID], [Country_ID], [Name]) VALUES (94, 1, N'Sevastopol')
SET IDENTITY_INSERT [dbo].[REGION] OFF
