INSERT INTO [dbo].[WINE] ([Wine_ID], [Grape_ID], [Name], [Wine_Type], [Description]) VALUES (N'Cabe9hnQ', N'Cabe9jfr', N'Cabernet Franc', N'Full-bodied red wine ', N'Strong spice aroma with powerful taste')
INSERT INTO [dbo].[WINE] ([Wine_ID], [Grape_ID], [Name], [Wine_Type], [Description]) VALUES (N'CabeOw97', N'Cabe17Z2', N'Cabernet Sauvignon ', N'Full-Bodied red wine', N'Spicy and aromotic ')
INSERT INTO [dbo].[WINE] ([Wine_ID], [Grape_ID], [Name], [Wine_Type], [Description]) VALUES (N'Gren81jI', N'Cham0lTg', N'Grenache', N'Rose', N'Fruity flavour ')
INSERT INTO [dbo].[WINE] ([Wine_ID], [Grape_ID], [Name], [Wine_Type], [Description]) VALUES (N'MerlPbe2', N'Merlt881', N'Merlot ', N'Medium-bodied wine', N'Pepper taste with strong red fruit aroma ')
INSERT INTO [dbo].[WINE] ([Wine_ID], [Grape_ID], [Name], [Wine_Type], [Description]) VALUES (N'OakeRF95', N'CharRR72', N'Oaked Chardonnay', N'Full-Bodied white wines', N'Vanilla flavour')
INSERT INTO [dbo].[WINE] ([Wine_ID], [Grape_ID], [Name], [Wine_Type], [Description]) VALUES (N'PinoKy6f', N'PinoR67s', N'Pinot Noir', N'Light-Bodied red wine', N'Aroma of fruits with a soft taste')
INSERT INTO [dbo].[WINE] ([Wine_ID], [Grape_ID], [Name], [Wine_Type], [Description]) VALUES (N'Sang7hhE', N'CottR330', N'Sangiovese', N'Rose', N'Melon flavour')
INSERT INTO [dbo].[WINE] ([Wine_ID], [Grape_ID], [Name], [Wine_Type], [Description]) VALUES (N'SyraO91b', N'LembI976', N'Syrah ', N'Full-bodied red wine', N'Leather aroma and sour cherry taste')
