INSERT INTO [dbo].[GRAPE] ([Grape_ID], [Name], [Grape_Type], [Description]) VALUES (N'Cabe17Z2', N'Cabernet Sauvignon', N'Red', N'Requires little to no care to grow healthily')
INSERT INTO [dbo].[GRAPE] ([Grape_ID], [Name], [Grape_Type], [Description]) VALUES (N'Cabe9jfr', N'Cabenet Franc', N'Red', N'Full bodied aromatic and textured')
INSERT INTO [dbo].[GRAPE] ([Grape_ID], [Name], [Grape_Type], [Description]) VALUES (N'Cham0lTg', N'Champagne', N'White', N'Sweet taste soft texture ')
INSERT INTO [dbo].[GRAPE] ([Grape_ID], [Name], [Grape_Type], [Description]) VALUES (N'CharRR72', N'Chardonney', N'White', N'Soft skin sweet taste ')
INSERT INTO [dbo].[GRAPE] ([Grape_ID], [Name], [Grape_Type], [Description]) VALUES (N'Chen00p1', N'Chenin Blanc', N'White', N'Tightly bunched with clean taste')
INSERT INTO [dbo].[GRAPE] ([Grape_ID], [Name], [Grape_Type], [Description]) VALUES (N'Conc4tfU', N'Concord', N'Red', N'Sweet table grapes')
INSERT INTO [dbo].[GRAPE] ([Grape_ID], [Name], [Grape_Type], [Description]) VALUES (N'CottR330', N'Cotton Candy', N'White', N'Cotton candy taste ')
INSERT INTO [dbo].[GRAPE] ([Grape_ID], [Name], [Grape_Type], [Description]) VALUES (N'GewuYY89', N'Gewurztraminer', N'White', N'Clean sweet taste')
INSERT INTO [dbo].[GRAPE] ([Grape_ID], [Name], [Grape_Type], [Description]) VALUES (N'KyohYv60', N'Kyoho', N'Red', N'Light and juicy taste')
INSERT INTO [dbo].[GRAPE] ([Grape_ID], [Name], [Grape_Type], [Description]) VALUES (N'LembI976', N'Lemburger', N'Red', N'Dark purple colour spicy taste')
INSERT INTO [dbo].[GRAPE] ([Grape_ID], [Name], [Grape_Type], [Description]) VALUES (N'Merlt881', N'Merlot', N'Red', N'Juicy and sweet when ripe')
INSERT INTO [dbo].[GRAPE] ([Grape_ID], [Name], [Grape_Type], [Description]) VALUES (N'Moon53bG', N'Moon drops', N'Red', N'Seedless sweet grape')
INSERT INTO [dbo].[GRAPE] ([Grape_ID], [Name], [Grape_Type], [Description]) VALUES (N'Musc44Po', N'Muscadine', N'Red', N'Skin is thick and quite hard')
INSERT INTO [dbo].[GRAPE] ([Grape_ID], [Name], [Grape_Type], [Description]) VALUES (N'PinoDDxc', N'Pinotgris', N'White', N'Greyish pink skin ')
INSERT INTO [dbo].[GRAPE] ([Grape_ID], [Name], [Grape_Type], [Description]) VALUES (N'PinoR67s', N'Pinot Noir', N'Red', N'Thin skin with a medium-sized body')
INSERT INTO [dbo].[GRAPE] ([Grape_ID], [Name], [Grape_Type], [Description]) VALUES (N'RiesMpp0', N'Riesling', N'White', N'Sweet taste solid bunches')
INSERT INTO [dbo].[GRAPE] ([Grape_ID], [Name], [Grape_Type], [Description]) VALUES (N'Sauv2njO', N'Sauvignon Blanc', N'White', N'Early ripening grape soft texture')
INSERT INTO [dbo].[GRAPE] ([Grape_ID], [Name], [Grape_Type], [Description]) VALUES (N'SemiP00x', N'Semillon', N'White', N'Sweet taste soft skin')
INSERT INTO [dbo].[GRAPE] ([Grape_ID], [Name], [Grape_Type], [Description]) VALUES (N'SweeN997', N'Sweet Jubilee', N'White', N'Sweet and clean taste')
INSERT INTO [dbo].[GRAPE] ([Grape_ID], [Name], [Grape_Type], [Description]) VALUES (N'Viog0bby', N'Viognier', N'White', N'Aromatic and textured ')
